toolsroot="${OE_BASE}/build-${DISTRO}/tmp/sysroots/`uname -m`-`uname -s | awk '{print tolower($0)}'`/usr"
sysroot="${OE_BASE}/build-${DISTRO}/tmp/sysroots/armv7a-linux-gnueabi"
if [ ! `echo ${PATH} | grep arm7a/bin` ]; then
	export PATH="${toolsroot}/bin:${toolsroot}/armv7a/bin:${PATH}"
fi
COMPILER_PREFIX="arm-linux-gnueabi-"
export CPP="${COMPILER_PREFIX}gcc -E --sysroot=${sysroot} -march=armv7-a -mtune=cortex-a9 -mfpu=neon -mfloat-abi=hardfp -mthumb-interwork"
export CC="${COMPILER_PREFIX}gcc --sysroot=${sysroot} -march=armv7-a -mtune=cortex-a9 -mfpu=neon -mfloat-abi=hardfp -mthumb-interwork"
export AS="${COMPILER_PREFIX}as"
export AR="${COMPILER_PREFIX}ar"
export NM="${COMPILER_PREFIX}nm"
export STRIP="${COMPILER_PREFIX}strip"
export OBJCOPY="${COMPILER_PREFIX}objcopy"
export RANLIB="${COMPILER_PREFIX}ranlib"
export LD="${COMPILER_PREFIX}ld --sysroot=${sysroot}"
#export CFLAGS="-fno-tree-vectorize -fomit-frame-pointer -O4 -frename-registers -ffast-math"
export DCE_CFLAGS="-I$sysroot/usr/include/dce"
export DCE_LDFLAGS="-ldce"
export AV_CFLAGS=""
export AV_LDFLAGS="-lpthread -lavformat -lavcodec"
export GLES_CFLAGS=""
export GLES_LDFLAGS="-lEGL -lGLESv2"
